var d=null,e="http://chinamaps.googlecode.com/svn/mapplets/euro2008/",f=e+"euro08_data",k=null,q=[0,1,2,3],r=[false,false,false,false,false],s=[null,null,null,null,null],aa=[true,true,false,false,false],v=new GMap2,y="",z="",A=null,ba=new GLatLng(47.249407,11.447754),ca=true,B="div",C="br",E="1px",F="MSG_team_",G="8px",H="Verdana,Arial,Helvetica,Sans-Serif",I="filter_team",K="filter_stadium",L="filter_group",M="additional_element",da={vie:"http://wien.info/article.asp?IDArticle=16460",kla:"http://carinthia.nethotels.com/nethotels/deutsch/woerthersee_stadion",
sal:"http://salzburg.nethotels.com/stadion_wals-siezenheim",inn:"http://tirol.nethotels.com/nethotels/deutsch/tivoli-stadion",zrh:"http://euro.zuerich.com/de.cfm/euro2008/stadion/",gen:"http://www.polyglott.de/service/em-special_2821.html?utm_source=Google%2BMaps&utm_medium=Anzeige&utm_content=Genf%2BSTadion&utm_campaign=EM-Special",bas:"http://www.polyglott.de/service/em-special_2813.html?utm_source=Google%2BMaps&utm_medium=Anzeige&utm_content=Basel%2BStadion&utm_campaign=EM-Special",ber:"http://www.stadedesuisse.ch/"};
function ea(){var a=d.blogs.ALL.blog_url+d.blogs.ALL.data_path;_IG_FetchContent(a,function(b){if(b.search(/__DATA_AKPJCQ__(.*)__DATA_AKPJCQ__/)!=-1){b=RegExp.$1;k=N("("+b+")");fa(ca)}},{refreshInterval:180})}function ia(a){var b="http://news.google.com/news?hl="+O(MSG_lang)+"&ned="+O(MSG_lang)+"&q=uefa+euro+2008&ie=UTF-8&output=atom";_IG_FetchXmlContent(b,function(c){a(ja(c))})}function ja(a){var b=[],c=a.getElementsByTagName("entry");for(var h=0;h<P(c);h++){var g=c[h],i={},j=["title","content"];
for(var l=0;l<P(j);++l)i[j[l]]=g.getElementsByTagName(j[l])[0].childNodes[0].nodeValue;i.link=g.getElementsByTagName("link").href;b.push(i)}return b}function ka(a){if(!d){window.setTimeout(function(){ka(a)},100);return}var b=document.getElementById("news_div");b.innerHTML="";Q(b,R(C));var c=R("fieldset");T(c).borderColor="#d3d9c5";T(c).borderWidth=E;T(c).padding=G;var h=U(MSG_news+": "),g=R("b");Q(g,h);var i=R("legend");Q(i,g);Q(c,i);for(var j=0;j<P(a)&&j<5;j++){var l=R(B);l.innerHTML=a[j].content;
T(l).borderBottom="solid 1px #d3d9c5";T(l).paddingBottom=G;T(l).paddingTop=G;Q(c,l)}Q(b,c);_IG_AdjustIFrameHeight();window.setTimeout(function(){var m=b.getElementsByTagName("a");for(var n=0;n<P(m);++n){var o=m[n];if(o.href&&o.href.search("http://news.google.com")==0)o.target="news_window"}},0)}function la(){if(!d){window.setTimeout(la,100);return}ia(ka)}function ma(a){switch(a){case 0:return MSG_cat_title_teams;case 1:return MSG_cat_title_stadiums;case 2:return MSG_photos;case 3:return MSG_cat_title_bars_clubs;
case 4:return MSG_wikipedia}return""}function na(a){var b=3,c=R(B);T(c).fontFamily=H;T(c).fontSize="12px";T(c).width="577px";var h=R("img");h.src=e+"flag_"+a+"_"+V()+".png";T(h).width="455px";T(h).height="75px";Q(c,h);var g=R("h3");Q(g,U(MSG_squad_list+": "+N(F+a)));Q(c,g);var i=R("i"),j=R("p");Q(i,U(MSG_coach+": "+d.players[a].t));Q(j,i);var l={k:MSG_goalkeepers,d:MSG_defenders,m:MSG_midfielders,f:MSG_forwards},m={k:"#55820a",d:"#a0c02a",m:"#55820a",f:"#a0c02a"};for(var n in l){var o=R("b");Q(o,
U(l[n]));Q(c,o);var t=R(B);T(t).borderColor=m[n];T(t).borderWidth=E;T(t).padding="5px";T(t).borderStyle="solid";var p=R("table");p.width="100%";var u=R("tbody"),w=d.players[a][n],x=P(w);for(var i=0;i<Math.ceil(x/b);++i){var D=R("tr");for(var J=0;J<b;++J){var Z=R("td"),ga=i*b+J;if(ga<x)Q(Z,U(w[ga]));else Q(Z,U(" "));Q(D,Z)}Q(u,D)}Q(p,u);Q(t,p);Q(c,t);Q(c,R(C))}var Ea=W(),S=X(true);T(S).display="inline";T(S).position="relative";T(S).padding="3px";Q(c,oa(Ea,S));var ha=R(C);T(ha).clear="left";Q(c,ha);
return c}function oa(a,b){var c=R("table");c.cellPadding="0";c.border="0";T(c).border="0px";T(c).width="100%";var h=R("tbody"),g=R("tr"),i=R("td"),j=R("td");T(i).textAlign="left";T(j).textAlign="right";Q(i,a);Q(j,b);Q(g,i);Q(g,j);Q(h,g);Q(c,h);return c}function pa(a,b){var c=qa(b),h=R(B);T(h).width="577px";Q(h,ra(c,b));var g=W();T(g).fontSize="12px";T(g).fontFamily=H;Q(h,g);return h}function sa(a){var b=d.teams[a],c=new GInfoWindowTab(MSG_squad_list,na(a)),h={};h[I]=a;var g=new GInfoWindowTab(MSG_matches,
pa(b.name,h));b.marker.openInfoWindowTabs([c,g])}function ta(){sa(this.teamId)}function ua(a){return a=="zrh"||a=="bas"||a=="ber"||a=="gen"?"sui":"aut"}function va(a){if(a=="kla"||a=="sal"||a=="inn")return"\u00a9 nethotels.com";var b="...mehr von ";switch(a){case "vie":b+="Wien Tourismus";break;case "zrh":b+="Z\u00fcrich Tourismus";break;case "ber":b+="Bern Tourismus";break;case "gen":case "bas":b+="polyglott.de";break}return b}function wa(a){var b="\u00a9 ";switch(a){case "vie":b+="Wien Tourismus";
break;case "kla":case "sal":case "inn":b+="nethotels.com";break;case "zrh":b+="Zurich Tourismus";break;case "ber":b+="Bern Tourismus";break;case "gen":case "bas":b+="Berlitz";break}return b}function xa(a){var b=R(B);if(MSG_lang=="de"){var c=U(va(a)),h=R("a");h.href=da[a];h.target="_new";Q(h,c);Q(b,h)}else{var c=U(wa(a)+" ");Q(b,c);var g=a=="gen"||a=="bas"?"berlitz_logo.png":"";if(g!=""){var i=R("img");i.src=e+g;T(i).width="45px";T(i).height="15px";Q(b,i)}}return b}function ya(a){var b=R(B);T(b).width=
"577px";T(b).minHeight="377px";T(b).fontFamily=H;T(b).fontSize="10px";var c=R("img");c.src=e+"flag_"+ua(a)+"_"+V()+".png";T(c).width="455px";T(c).height="75px";Q(b,c);Q(b,R(C));var h=R("b");Q(h,U(N("MSG_sta_"+a)));Q(b,h);var g=R(B);T(g).borderColor="#ccc";T(g).borderWidth=E;T(g).padding=G;T(g).borderStyle="solid";var i=R("table");i.bgColor="#F0F1F2";i.width="100%";var j=R("tbody"),l=R("tr"),m=R("td");T(m).padding="10px";var n=R("img");n.src=e+"sta_"+a+".png";T(n).width="211px";T(n).height="141px";
Q(m,n);Q(m,R(C));Q(m,U("\u00a9 dpa"));var o=[];o.push([MSG_capacity+": ",d.stadiums[a].cap]);o.push([MSG_covered_seats+": ",d.stadiums[a].seats_cov]);o.push([MSG_location+": ",N("MSG_hc_"+a)]);o.push([MSG_country+": ",N("MSG_team_"+ua(a))]);var t=R("td");T(t).padding="10px";for(var p=0;p<P(o);++p){var h=R("b");Q(h,U(o[p][0]));Q(t,h);Q(t,U(o[p][1]));Q(t,R(C))}Q(l,m);Q(l,t);Q(j,l);Q(i,j);Q(g,i);var u=N("MSG_iw_sta_"+a);u=u.replace(/&lt;/g,"<");u=u.replace(/&gt;/g,">");var w=u.split("<br />");for(var p=
0;p<P(w);++p){var x=R("p");x.innerHTML=w[p];Q(g,x)}Q(g,xa(a));Q(b,g);Q(b,R(C));var x=za(a),D=X(true);T(D).display="inline";T(D).position="relative";T(D).padding="3px";Q(b,oa(x,D));var J=R(C);T(J).clear="left";Q(b,J);return b}function za(a){var b=R(B);if(!Aa(["ALL","cs","de","es","it","nl","pl","ru","sv","fr"],MSG_lang))return b;try{var c=R("a");c.href=eval("MSG_tr_sta_"+a).replace(/&amp;/g,"&");var h=U(MSG_transit);Q(c,h);Q(b,c)}catch(g){return R(B)}return b}function Ba(a){var b=d.stadiums[a],c=new GInfoWindowTab(MSG_information,
ya(a)),h={};h[K]=a;var g=new GInfoWindowTab(MSG_matches,pa(b.name,h));b.marker.openInfoWindowTabs([c,g])}function Ca(){Ba(this.stadiumId)}function Da(a){var b=new GIcon(G_DEFAULT_ICON);b.image=e+"team_"+a+".png";b.shadow=e+"shadow.png";b.shadowSize=new GSize(52,47);b.infoShadowAnchor=new GPoint(10,40);b.iconSize=new GSize(33,47);b.iconAnchor=new GPoint(10,40);b.infoWindowAnchor=b.iconAnchor;b.imageMap=[0,1,29,1,32,17,28,19,18,17,8,17,12,35,15,40,13,45,8,45,5,42,6,39,8,36,5,20];return b}function Fa(){var a=
new GIcon(G_DEFAULT_ICON);a.image=e+"ball.png";a.shadow=null;a.iconSize=new GSize(43,37);a.iconAnchor=new GPoint(16,17);a.infoWindowAnchor=a.iconAnchor;a.imageMap=[1,10,10,1,23,1,22,9,32,21,31,24,23,32,12,32,1,22];return a}function Ga(){var a=R(B);T(a).fontFamily=H;T(a).fontSize="11px";T(a).fontSizeAdjust="none";T(a).width="477px";Q(a,Ha());d.marker.marker.openInfoWindow(a,{disableGoogleLinks:true})}function fa(a){var b=new GLatLng(d.marker.pos.lat,d.marker.pos.lng),c=new GMarker(b,{icon:Fa()});d.marker.marker=
c;GEvent.addListener(c,"click",Ga);v.addOverlay(c);if(a)Ga()}function Ia(){var a=new GIcon(G_DEFAULT_ICON);a.image=e+"stadium.png";a.shadow=null;a.iconSize=new GSize(64,30);a.iconAnchor=new GPoint(31,13);a.infoWindowAnchor=a.iconAnchor;a.imageMap=[31,1,40,1,61,9,59,14,50,20,27,27,9,22,3,17,3,14,0,11,10,7];return a}function Ja(){var a=[];for(var b in d.teams){var c=d.teams[b],h=new GLatLng(c.pos.lat,c.pos.lng),g=new GMarker(h,{icon:Da(b)});c.marker=g;g.teamId=b;GEvent.addListener(g,"click",ta);a.push(g)}return a}
function Ka(a){return[new GLayer(a)]}function La(){var a=[];for(var b in d.stadiums){var c=d.stadiums[b],h=new GLatLng(c.pos.lat,c.pos.lng),g=new GMarker(h,{icon:Ia()});g.stadiumId=b;GEvent.addListener(g,"click",Ca);c.marker=g;a.push(g)}return a}function Ma(a){switch(a){case 0:return Ja();case 1:return La();case 2:return Ka("lmc:panoramio");case 3:return Ka("lmc:bars_clubs");case 4:return Ka("lmc:wikipedia_en")}return[]}function Y(a){var b=document.getElementById("cat_"+a);if(!b.checked)b.checked=
true;if(r[a])return;if(!s[a])s[a]=Ma(a);for(var c=0;c<P(s[a]);c++)v.addOverlay(s[a][c]);r[a]=true}function Na(a){var b=document.getElementById("cat_"+a);if(b.checked)b.checked=false;if(!r[a])return;for(var c=0;c<P(s[a]);c++)v.removeOverlay(s[a][c]);r[a]=false}function Oa(){var a=this.value.split("_");if(P(a)!=2)return;var b=a[0],c=a[1];Pa(b,c)}function Qa(){var a=R(B),b=R("fieldset");T(b).borderColor="#a0c02a";T(b).borderWidth=E;T(b).padding=G;var c=R("select");c.onchange=Oa;var h=R("option");Q(h,
U(MSG_select_location));Q(c,h);var g=R("optgroup");g.label=MSG_cat_title_teams;var i=[],j={};for(n in d.teams){var l=N(F+n);i.push(l);j[l]=n}i.sort();for(var m=0;m<P(i);++m){var n=j[i[m]],o=R("option");Q(o,U(N(F+n)));o.value="team_"+n;Q(g,o)}Q(c,g);var t=R("optgroup");t.label=MSG_cat_title_stadiums;var p=[],u={};for(n in d.stadiums){var l=N("MSG_sta_"+n);p.push(l);u[l]=n}p.sort();for(var m=0;m<P(p);++m){var n=u[p[m]],o=R("option");Q(o,U(N("MSG_sta_"+n)));o.value="stadium_"+n;Q(t,o)}Q(c,t);var w=R("legend"),
x=R("b");Q(x,U(MSG_zoom_into_location+": "));Q(w,x);Q(b,w);Q(b,c);Q(a,b);return a}function V(){if(MSG_lang=="de"||MSG_lang=="es"||MSG_lang=="fr"||MSG_lang=="it"||MSG_lang=="nl"||MSG_lang=="ru")return MSG_lang;return"ALL"}function Ra(){var a=document.getElementById("controls"),b=R("img");T(b).width="158px";T(b).height="70px";b.src=e+"23days_logo_"+V()+".png";Q(a,b);var c=R("fieldset");T(c).borderColor="#ccc";T(c).borderWidth=E;T(c).padding="5px";Q(c,X(false));Q(a,R(C));Q(a,c);var h=R("p"),g=R("i");
Q(g,U(MSG_description_new+": "));Q(h,g);Q(a,h);var i=R("fieldset");T(i).borderColor="#55820a";T(i).borderWidth=E;T(i).padding="5px";var j=R("legend"),l=R("b");Q(l,U(MSG_display_on_the_map+": "));Q(j,l);Q(i,j);var m=[R(B),R(B)];$(m[0],"left");$(m[1],"right");var n=[];for(g=0;g<P(q);g++){var o=R("input");o.type="checkbox";o.id="cat_"+q[g];o.catNr=q[g];o.onclick=function(){if(this.checked)Y(this.catNr);else Na(this.catNr)};if(aa[g])n.push(q[g]);var t=U(ma(q[g])),p=R(C),u=q[g],w=u==0||u==1?0:1;Q(m[w],
o);Q(m[w],t);Q(m[w],p)}Q(i,m[0]);Q(i,m[1]);Q(a,i);Q(a,R(C));Q(a,Qa());window.setTimeout(function(){for(var x=0;x<P(n);++x)Y(n[x])},0)}function Sa(a){var b=document.location.search,c=b.indexOf(a+"=");if(c==-1)return"";var h=b.substr(c+P(a)+1,P(b)-c-P(a)-1);c=h.indexOf("&");if(c!=-1)h=h.substr(0,c);return h}function Ta(){if(A)Ua();A=setInterval(Va,100)}function Ua(){if(A){clearInterval(A);A=null}}function Pa(a,b){if(a=="team")v.setZoom(9);else v.setZoom(16);switch(a){case "team":Y(0);sa(b);break;case "stadium":Y(1);
Ba(b);break}}function Va(){Ua();var a=document.location.hash;if(P(a)>1){document.location.href=y+"#";a=a.replace("#","");var b=a.split("_");if(P(b)>0)switch(b[0]){case "goto":P(b)==3&&Pa(b[1],b[2]);break}}Ta()}function Wa(a){if(!d||!d.stadiums||!d.stadiums[a]||!k){window.setTimeout(function(){Wa(a)},100);return}Pa("stadium",a);Y(2)}function _init(){v.setMapType(G_HYBRID_MAP);y=document.location.href;z=Sa("fid");var a=unescape(Sa("url")),b=a.split("#"),c=false;if(P(b)>1){var h=b[1].split("_");if(h[0]==
"sta"&&P(h)==2){c=true;Wa(h[1])}}if(!c)v.setCenter(ba,4);else ca=false;Ta();var g=O(MSG_lang),i=f+".js";if(g=="cn")i=f+"_cn.js";else if(g=="hk")i=f+"_hk.js";_IG_FetchContent(i,function(j){d=N("("+j+")");Ra();_IG_AdjustIFrameHeight();ea()});la()}function qa(a){if(!a)a={};var b=[];for(var c=0;c<P(k.matches);c++){var h=k.matches[c];if(a[I]&&a[I]!=h.home&&a[I]!=h.away)continue;if(a[L]&&a[L]!=h.group)continue;if(a[K]&&a[K]!=h.stadium)continue;b.push(h)}return b}function Xa(a,b,c){if(!c)c={};var h=null;
if(c[M])h=c[M];var g=R("tr");T(g).border="1px solid gray";for(var i=0;i<P(b);i++){var j=R("td");T(j).border="1px solid gray";if(h){var l=R(h);Q(l,b[i]);Q(j,l)}else Q(j,b[i]);Q(g,j)}Q(a,g)}function Ya(a,b){var c=U(a);if(!z)return c;var h=y+"#goto_"+b,g=R("a");g.href=h;g.target=z;Q(g,c);return g}function Za(a){if(!a||a=="")return U("");return Ya(N(F+a),"team_"+a)}function ra(a,b){if(!b)b={};var c=R(B);T(c).fontFamily=H;T(c).fontSize="11px";T(c).fontSizeAdjust="none";var h=R(B);T(h).borderColor="#ccc";
T(h).borderWidth=E;T(h).padding=G;T(h).borderStyle="solid";var g=R("span");T(g).fontSize="14px";T(g).fontWeight="bold";var i=MSG_match_schedule;if(b[K])i=i+": "+N("MSG_sta_"+b[K]);else if(b[L])i=i+": "+N("MSG_group_"+b[L]);else if(b[I])i=i+": "+N(F+b[I]);var j=R("b");Q(j,U(i));Q(c,j);Q(h,g);var l=R("table");T(l).border="0px";T(l).borderCollapse="collapse";T(l).width="100%";var m=R("tbody"),n=[U(MSG_grp),U(MSG_date),U(MSG_time),U(" "),U(" "),U(MSG_stadium),U(MSG_score)],o={};o[M]="b";Xa(m,n,o);for(var t=
0;t<P(a);t++){var p=a[t],u=MSG_date_format;u=u.replace(/%YY/,p.date[2]);u=u.replace(/%MM/,p.date[1]);u=u.replace(/%DD/,p.date[0]);var w=MSG_time_format;w=w.replace(/%HH/,p.time[0]);w=w.replace(/%MM/,p.time[1]);var x=[U(p.group),U(u),U(w),Za(p.home),Za(p.away),Ya(N("MSG_sta_"+p.stadium),"stadium_"+p.stadium),U(p.score)];Xa(m,x)}Q(l,m);Q(h,l);Q(c,h);return c}function $a(a,b){var c=["","",MSG_matches_played_abbr,MSG_matches_won_abbr,MSG_matches_drawn_abbr,MSG_matches_lost_abbr,MSG_goals_for_abbr,MSG_goals_against_abbr,
MSG_points_won_abbr];function h(j){var l=R("tr");T(l).border="1px solid gray";for(var m=0;m<P(j);++m){var n=R("td");Q(n,U(j[m]));Q(l,n)}Q(b,l)}h(c);for(var g=0;g<P(a);++g){var i=a[g],c=[i.pos,N(F+i.team),i.p,i.w,i.d,i.l,i.gf,i.ga,i.pts];h(c)}}function ab(){var a=R(B);$(a,"left");T(a).width="250px";var b={A:"#55820a",B:"#a0c02a",C:"#55820a",D:"#a0c02a"};for(var c in k.groups){var h=R("span");T(h).fontWeight="bold";Q(h,U(N("MSG_group_"+c)));Q(a,h);var g=R(B);T(g).borderColor=b[c];T(g).borderWidth=E;
T(g).padding=G;T(g).borderStyle="solid";var i=R("table");T(i).border="0px";T(i).borderCollapse="collapse";T(i).width="100%";var j=R("tbody");$a(k.groups[c],j);Q(i,j);Q(g,i);Q(a,g);Q(a,R(C))}return a}function bb(){var a=R(B);$(a,"right");T(a).marginRight="5px";T(a).width="130px";var b=R("b");Q(b,U(MSG_legend+":"));Q(a,b);Q(a,R(C));var c=R(B);T(c).borderColor="#ccc";T(c).borderWidth=E;T(c).padding=G;T(c).borderStyle="solid";var h=["matches_played","matches_won","matches_drawn","matches_lost","goals_for",
"goals_against","points_won"];for(var g=0;g<P(h);++g){var i=h[g],b=R("b");Q(b,U(N("MSG_"+i+"_abbr")+": "));Q(c,b);Q(c,U(N("MSG_"+i)));Q(c,R(C))}Q(a,c);return a}function Aa(a,b){for(var c=0;c<P(a);++c)if(a[c]==b)return true;return false}function O(a,b){if(!b)b=[];return a=="ALL"||Aa(b,a)?"en":a}function X(a){var b=R(B);if(a){T(b).borderColor="#ccc";T(b).borderWidth=E;T(b).borderStyle="solid"}var c=R("a");c.href="http://maps.google.com/support/bin/answer.py?hl="+O(MSG_lang,["cs","pl"])+"&answer=68480";
c.target="_new";Q(c,U(MSG_mymaps));Q(b,c);return b}function W(){var a=R(B);if(MSG_lang=="de"){var b=R("a");b.href="http://www.kicker.de/em";b.target="_new";Q(b,U("...mehr von kicker.de"));Q(a,b)}else Q(a,U("\u00a9 kicker online"));return a}function Ha(){var a=R(B);T(a).padding="5px";var b=R("h3");T(b).fontWeight="bold";Q(b,U(MSG_group_standings));Q(a,b);var c=R("table");T(c).border="0px";T(c).width="100%";var h=R("tbody"),g=R("tr"),i=R("td");Q(i,ab());var j=R("td");T(j).verticalAlign="top";Q(j,bb());
Q(g,i);Q(g,j);Q(h,g);Q(c,h);Q(a,c);var l=W(),m=X(true);T(m).display="inline";T(m).position="relative";T(m).padding="3px";Q(a,oa(l,m));var n=R(C);T(n).clear="left";Q(a,n);return a}function R(a){return document.createElement(a)}function U(a){return document.createTextNode(a)}function Q(a,b){a.appendChild(b)}function T(a){return a.style}function P(a){return a.length}function N(a){return eval(a)}function $(a,b){if(a.style.styleFloat===undefined)a.style.cssFloat=b;else a.style.styleFloat=b};
