var c=null,e="http://chinamaps.googlecode.com/svn/mapplets/euro2008/",f=e+"euro08_data",k=null,q=[0,1,2,3],r=[false,false,false,false,false],u=[null,null,null,null,null],ca=[true,true,false,false,false],v=new GMap2,x="",z="",A=null,da=new GLatLng(47.249407,11.447754),ea=true,B="div",C="br",D="1px",F="MSG_team_",G="8px",H="Verdana,Arial,Helvetica,Sans-Serif",I="filter_team",J="filter_stadium",K="filter_group",L="additional_element";function fa(){var a=c.blogs.ALL.blog_url+c.blogs.ALL.data_path;_IG_FetchContent(a,
function(b){if(b.search(/__DATA_AKPJCQ__(.*)__DATA_AKPJCQ__/)!=-1){b=RegExp.$1;k=M("("+b+")");ga(ea)}},{refreshInterval:180})}function ia(a){var b="http://news.google.com/news?hl="+P(MSG_lang)+"&ned="+P(MSG_lang)+"&q=uefa+euro+2008&ie=UTF-8&output=atom";_IG_FetchXmlContent(b,function(d){a(ja(d))})}function ja(a){var b=[],d=a.getElementsByTagName("entry");for(var h=0;h<Q(d);h++){var g=d[h],i={},l=["title","content"];for(var j=0;j<Q(l);++j)i[l[j]]=g.getElementsByTagName(l[j])[0].childNodes[0].nodeValue;
i.link=g.getElementsByTagName("link").href;b.push(i)}return b}function ka(a){if(!c){window.setTimeout(function(){ka(a)},100);return}var b=document.getElementById("news_div");b.innerHTML="";R(b,S(C));var d=S("fieldset");V(d).borderColor="#d3d9c5";V(d).borderWidth=D;V(d).padding=G;var h=W(MSG_news+": "),g=S("b");R(g,h);var i=S("legend");R(i,g);R(d,i);for(var l=0;l<Q(a)&&l<5;l++){var j=S(B);j.innerHTML=a[l].content;V(j).borderBottom="solid 1px #d3d9c5";V(j).paddingBottom=G;V(j).paddingTop=G;R(d,j)}R(b,
d);_IG_AdjustIFrameHeight();window.setTimeout(function(){var m=b.getElementsByTagName("a");for(var n=0;n<Q(m);++n){var o=m[n];if(o.href&&o.href.search("http://news.google.com")==0)o.target="news_window"}},0)}function la(){if(!c){window.setTimeout(la,100);return}ia(ka)}function ma(a){switch(a){case 0:return MSG_cat_title_teams;case 1:return MSG_cat_title_stadiums;case 2:return MSG_photos;case 3:return MSG_cat_title_bars_clubs;case 4:return MSG_wikipedia}return""}function na(a){var b=3,d=S(B);V(d).fontFamily=
H;V(d).fontSize="12px";V(d).width="577px";var h=S("img");h.src=e+"flag_"+a+"_"+X()+".png";V(h).width="455px";V(h).height="75px";R(d,h);var g=S("h3");R(g,W(MSG_squad_list+": "+M(F+a)));R(d,g);var i=S("i"),l=S("p");R(i,W(MSG_coach+": "+c.players[a].t));R(l,i);var j={k:MSG_goalkeepers,d:MSG_defenders,m:MSG_midfielders,f:MSG_forwards},m={k:"#55820a",d:"#a0c02a",m:"#55820a",f:"#a0c02a"};for(var n in j){var o=S("b");R(o,W(j[n]));R(d,o);var s=S(B);V(s).borderColor=m[n];V(s).borderWidth=D;V(s).padding="5px";
V(s).borderStyle="solid";var p=S("table");p.width="100%";var t=S("tbody"),w=c.players[a][n],y=Q(w);for(var i=0;i<Math.ceil(y/b);++i){var N=S("tr");for(var T=0;T<b;++T){var E=S("td"),O=i*b+T;if(O<y)R(E,W(w[O]));else R(E,W(" "));R(N,E)}R(t,N)}R(p,t);R(s,p);R(d,s);R(d,S(C))}var aa=S("div"),U=S("a");U.href="http://www.kicker.de/em";U.target="_new";R(U,W(MSG_copyright_kicker));R(aa,U);R(d,aa);Y(aa,"left");var ba=Z(true);Y(ba,"right");V(ba).padding="3px";R(d,ba);var ha=S(C);V(ha).clear="left";R(d,ha);return d}
function oa(a,b){var d=pa(b),h=S(B);V(h).width="577px";R(h,qa(d,b));var g=S("p");V(g).fontSize="12px";V(g).fontFamily=H;var i=S("a");i.href="http://www.kicker.de/em";i.target="_new";R(i,W(MSG_copyright_kicker));R(g,i);R(h,g);return h}function ra(a){var b=c.teams[a],d=new GInfoWindowTab(MSG_squad_list,na(a)),h={};h[I]=a;var g=new GInfoWindowTab(MSG_matches,oa(b.name,h));b.marker.openInfoWindowTabs([d,g])}function sa(){ra(this.teamId)}function ta(a){return a=="zrh"||a=="bas"||a=="ber"||a=="gen"?"sui":
"aut"}function ua(a){var b=S(B);V(b).width="577px";V(b).minHeight="377px";V(b).fontFamily=H;V(b).fontSize="10px";var d=S("img");d.src=e+"flag_"+ta(a)+"_"+X()+".png";V(d).width="455px";V(d).height="75px";R(b,d);R(b,S(C));var h=S("b");R(h,W(M("MSG_sta_"+a)));R(b,h);var g=S(B);V(g).borderColor="#ccc";V(g).borderWidth=D;V(g).padding=G;V(g).borderStyle="solid";var i=S("table");i.bgColor="#F0F1F2";i.width="100%";var l=S("tbody"),j=S("tr"),m=S("td");V(m).padding="10px";var n=S("img");n.src=e+"sta_"+a+".png";
V(n).width="211px";V(n).height="141px";R(m,n);R(m,S(C));R(m,W(MSG_copyright_photos));var o=[];o.push([MSG_capacity+": ",c.stadiums[a].cap]);o.push([MSG_covered_seats+": ",c.stadiums[a].seats_cov]);o.push([MSG_location+": ",M("MSG_hc_"+a)]);o.push([MSG_country+": ",M("MSG_team_"+ta(a))]);var s=S("td");V(s).padding="10px";for(var p=0;p<Q(o);++p){var h=S("b");R(h,W(o[p][0]));R(s,h);R(s,W(o[p][1]));R(s,S(C))}R(j,m);R(j,s);R(l,j);R(i,l);R(g,i);try{var t=M("MSG_iw_sta_"+a);t=t.replace(/&lt;/g,"<");t=t.replace(/&gt;/g,
">");var w=t.split("<br />");for(var p=0;p<Q(w);++p){var y=S("p");y.innerHTML=w[p];R(g,y)}var N="";N=a=="bas"||a=="gen"?MSG_copyright_stadiums2:MSG_copyright_stadiums1;R(g,W(N))}catch(T){}R(b,g);R(b,S(C));var E=Z(true);Y(E,"right");V(E).padding="3px";R(b,E);var O=S(C);V(O).clear="left";R(b,O);return b}function va(a){var b=c.stadiums[a],d=new GInfoWindowTab(MSG_information,ua(a)),h={};h[J]=a;var g=new GInfoWindowTab(MSG_matches,oa(b.name,h));b.marker.openInfoWindowTabs([d,g])}function wa(){va(this.stadiumId)}
function xa(a){var b=new GIcon(G_DEFAULT_ICON);b.image=e+"team_"+a+".png";b.shadow=e+"shadow.png";b.shadowSize=new GSize(52,47);b.infoShadowAnchor=new GPoint(10,40);b.iconSize=new GSize(33,47);b.iconAnchor=new GPoint(10,40);b.infoWindowAnchor=b.iconAnchor;b.imageMap=[0,1,29,1,32,17,28,19,18,17,8,17,12,35,15,40,13,45,8,45,5,42,6,39,8,36,5,20];return b}function ya(){var a=new GIcon(G_DEFAULT_ICON);a.image=e+"ball.png";a.shadow=null;a.iconSize=new GSize(43,37);a.iconAnchor=new GPoint(16,17);a.infoWindowAnchor=
a.iconAnchor;a.imageMap=[1,10,10,1,23,1,22,9,32,21,31,24,23,32,12,32,1,22];return a}function za(){var a=S(B);V(a).fontFamily=H;V(a).fontSize="11px";V(a).fontSizeAdjust="none";V(a).width="477px";R(a,Aa());c.marker.marker.openInfoWindow(a,{disableGoogleLinks:true})}function ga(a){var b=new GLatLng(c.marker.pos.lat,c.marker.pos.lng),d=new GMarker(b,{icon:ya()});c.marker.marker=d;GEvent.addListener(d,"click",za);v.addOverlay(d);if(a)za()}function Ba(){var a=new GIcon(G_DEFAULT_ICON);a.image=e+"stadium.png";
a.shadow=null;a.iconSize=new GSize(64,30);a.iconAnchor=new GPoint(31,13);a.infoWindowAnchor=a.iconAnchor;a.imageMap=[31,1,40,1,61,9,59,14,50,20,27,27,9,22,3,17,3,14,0,11,10,7];return a}function Ca(){var a=[];for(var b in c.teams){var d=c.teams[b],h=new GLatLng(d.pos.lat,d.pos.lng),g=new GMarker(h,{icon:xa(b)});d.marker=g;g.teamId=b;GEvent.addListener(g,"click",sa);a.push(g)}return a}function Da(a){return[new GLayer(a)]}function Ea(){var a=[];for(var b in c.stadiums){var d=c.stadiums[b],h=new GLatLng(d.pos.lat,
d.pos.lng),g=new GMarker(h,{icon:Ba()});g.stadiumId=b;GEvent.addListener(g,"click",wa);d.marker=g;a.push(g)}return a}function Fa(a){switch(a){case 0:return Ca();case 1:return Ea();case 2:return Da("lmc:panoramio");case 3:return Da("lmc:bars_clubs");case 4:return Da("lmc:wikipedia_en")}return[]}function $(a){var b=document.getElementById("cat_"+a);if(!b.checked)b.checked=true;if(r[a])return;if(!u[a])u[a]=Fa(a);for(var d=0;d<Q(u[a]);d++)v.addOverlay(u[a][d]);r[a]=true}function Ga(a){var b=document.getElementById("cat_"+
a);if(b.checked)b.checked=false;if(!r[a])return;for(var d=0;d<Q(u[a]);d++)v.removeOverlay(u[a][d]);r[a]=false}function Ha(){var a=this.value.split("_");if(Q(a)!=2)return;var b=a[0],d=a[1];Ia(b,d)}function Ja(){var a=S(B),b=S("fieldset");V(b).borderColor="#a0c02a";V(b).borderWidth=D;V(b).padding=G;var d=S("select");d.onchange=Ha;var h=S("option");R(h,W(MSG_select_location));R(d,h);var g=S("optgroup");g.label=MSG_cat_title_teams;var i=[],l={};for(n in c.teams){var j=M(F+n);i.push(j);l[j]=n}i.sort();
for(var m=0;m<Q(i);++m){var n=l[i[m]],o=S("option");R(o,W(M(F+n)));o.value="team_"+n;R(g,o)}R(d,g);var s=S("optgroup");s.label=MSG_cat_title_stadiums;var p=[],t={};for(n in c.stadiums){var j=M("MSG_sta_"+n);p.push(j);t[j]=n}p.sort();for(var m=0;m<Q(p);++m){var n=t[p[m]],o=S("option");R(o,W(M("MSG_sta_"+n)));o.value="stadium_"+n;R(s,o)}R(d,s);var w=S("legend"),y=S("b");R(y,W(MSG_zoom_into_location+": "));R(w,y);R(b,w);R(b,d);R(a,b);return a}function X(){if(MSG_lang=="de"||MSG_lang=="es"||MSG_lang==
"fr"||MSG_lang=="it"||MSG_lang=="nl"||MSG_lang=="ru")return MSG_lang;return"ALL"}function Ka(){var a=document.getElementById("controls"),b=S("img");V(b).width="158px";V(b).height="70px";b.src=e+"23days_logo_"+X()+".png";R(a,b);var d=S("fieldset");V(d).borderColor="#ccc";V(d).borderWidth=D;V(d).padding="5px";R(d,Z(false));R(a,S(C));R(a,d);var h=S("p"),g=S("i");R(g,W(MSG_description_new+": "));R(h,g);R(a,h);var i=S("fieldset");V(i).borderColor="#55820a";V(i).borderWidth=D;V(i).padding="5px";var l=S("legend"),
j=S("b");R(j,W(MSG_display_on_the_map+": "));R(l,j);R(i,l);var m=[S(B),S(B)];Y(m[0],"left");Y(m[1],"right");var n=[];for(g=0;g<Q(q);g++){var o=S("input");o.type="checkbox";o.id="cat_"+q[g];o.catNr=q[g];o.onclick=function(){if(this.checked)$(this.catNr);else Ga(this.catNr)};if(ca[g])n.push(q[g]);var s=W(ma(q[g])),p=S(C),t=q[g],w=t==0||t==1?0:1;R(m[w],o);R(m[w],s);R(m[w],p)}R(i,m[0]);R(i,m[1]);R(a,i);R(a,S(C));R(a,Ja());window.setTimeout(function(){for(var y=0;y<Q(n);++y)$(n[y])},0)}function La(a){var b=
document.location.search,d=b.indexOf(a+"=");if(d==-1)return"";var h=b.substr(d+Q(a)+1,Q(b)-d-Q(a)-1);d=h.indexOf("&");if(d!=-1)h=h.substr(0,d);return h}function Ma(){if(A)Na();A=setInterval(Oa,100)}function Na(){if(A){clearInterval(A);A=null}}function Ia(a,b){if(a=="team")v.setZoom(9);else v.setZoom(16);switch(a){case "team":$(0);ra(b);break;case "stadium":$(1);va(b);break}}function Oa(){Na();var a=document.location.hash;if(Q(a)>1){document.location.href=x+"#";a=a.replace("#","");var b=a.split("_");
if(Q(b)>0)switch(b[0]){case "goto":Q(b)==3&&Ia(b[1],b[2]);break}}Ma()}function Pa(a){if(!c||!c.stadiums||!c.stadiums[a]||!k){window.setTimeout(function(){Pa(a)},100);return}Ia("stadium",a);$(2)}function _init(){v.setMapType(G_HYBRID_MAP);x=document.location.href;z=La("fid");var a=unescape(La("url")),b=a.split("#"),d=false;if(Q(b)>1){var h=b[1].split("_");if(h[0]=="sta"&&Q(h)==2){d=true;Pa(h[1])}}if(!d)v.setCenter(da,4);else ea=false;Ma();var g=P(MSG_lang),i=f+".js";if(g=="cn")i=f+"_cn.js";_IG_FetchContent(f,
function(l){c=M("("+l+")");Ka();_IG_AdjustIFrameHeight();fa()});la()}function pa(a){if(!a)a={};var b=[];for(var d=0;d<Q(k.matches);d++){var h=k.matches[d];if(a[I]&&a[I]!=h.home&&a[I]!=h.away)continue;if(a[K]&&a[K]!=h.group)continue;if(a[J]&&a[J]!=h.stadium)continue;b.push(h)}return b}function Qa(a,b,d){if(!d)d={};var h=null;if(d[L])h=d[L];var g=S("tr");V(g).border="1px solid gray";for(var i=0;i<Q(b);i++){var l=S("td");V(l).border="1px solid gray";if(h){var j=S(h);R(j,b[i]);R(l,j)}else R(l,b[i]);R(g,
l)}R(a,g)}function Ra(a,b){var d=W(a);if(!z)return d;var h=x+"#goto_"+b,g=S("a");g.href=h;g.target=z;R(g,d);return g}function Sa(a){if(!a||a=="")return W("");return Ra(M(F+a),"team_"+a)}function qa(a,b){if(!b)b={};var d=S(B);V(d).fontFamily=H;V(d).fontSize="11px";V(d).fontSizeAdjust="none";var h=S(B);V(h).borderColor="#ccc";V(h).borderWidth=D;V(h).padding=G;V(h).borderStyle="solid";var g=S("span");V(g).fontSize="14px";V(g).fontWeight="bold";var i=MSG_match_schedule;if(b[J])i=i+": "+M("MSG_sta_"+b[J]);
else if(b[K])i=i+": "+M("MSG_group_"+b[K]);else if(b[I])i=i+": "+M(F+b[I]);var l=S("b");R(l,W(i));R(d,l);R(h,g);var j=S("table");V(j).border="0px";V(j).borderCollapse="collapse";V(j).width="100%";var m=S("tbody"),n=[W(MSG_grp),W(MSG_date),W(MSG_time),W(" "),W(" "),W(MSG_stadium),W(MSG_score)],o={};o[L]="b";Qa(m,n,o);for(var s=0;s<Q(a);s++){var p=a[s],t=MSG_date_format;t=t.replace(/%YY/,p.date[2]);t=t.replace(/%MM/,p.date[1]);t=t.replace(/%DD/,p.date[0]);var w=MSG_time_format;w=w.replace(/%HH/,p.time[0]);
w=w.replace(/%MM/,p.time[1]);var y=[W(p.group),W(t),W(w),Sa(p.home),Sa(p.away),Ra(M("MSG_sta_"+p.stadium),"stadium_"+p.stadium),W(p.score)];Qa(m,y)}R(j,m);R(h,j);R(d,h);return d}function Ta(a,b){var d=["","",MSG_matches_played_abbr,MSG_matches_won_abbr,MSG_matches_drawn_abbr,MSG_matches_lost_abbr,MSG_goals_for_abbr,MSG_goals_against_abbr,MSG_points_won_abbr];function h(l){var j=S("tr");V(j).border="1px solid gray";for(var m=0;m<Q(l);++m){var n=S("td");R(n,W(l[m]));R(j,n)}R(b,j)}h(d);for(var g=0;g<
Q(a);++g){var i=a[g],d=[i.pos,M(F+i.team),i.p,i.w,i.d,i.l,i.gf,i.ga,i.pts];h(d)}}function Ua(){var a=S(B);Y(a,"left");V(a).width="250px";var b={A:"#55820a",B:"#a0c02a",C:"#55820a",D:"#a0c02a"};for(var d in k.groups){var h=S("span");V(h).fontWeight="bold";R(h,W(M("MSG_group_"+d)));R(a,h);var g=S(B);V(g).borderColor=b[d];V(g).borderWidth=D;V(g).padding=G;V(g).borderStyle="solid";var i=S("table");V(i).border="0px";V(i).borderCollapse="collapse";V(i).width="100%";var l=S("tbody");Ta(k.groups[d],l);R(i,
l);R(g,i);R(a,g);R(a,S(C))}return a}function Va(){var a=S(B);Y(a,"right");V(a).marginRight="5px";V(a).width="130px";var b=S("b");R(b,W(MSG_legend+":"));R(a,b);R(a,S(C));var d=S(B);V(d).borderColor="#ccc";V(d).borderWidth=D;V(d).padding=G;V(d).borderStyle="solid";var h=["matches_played","matches_won","matches_drawn","matches_lost","goals_for","goals_against","points_won"];for(var g=0;g<Q(h);++g){var i=h[g],b=S("b");R(b,W(M("MSG_"+i+"_abbr")+": "));R(d,b);R(d,W(M("MSG_"+i)));R(d,S(C))}R(a,d);return a}
function P(a){return a=="ALL"?"en":a}function Z(a){var b=S(B);if(a){V(b).borderColor="#ccc";V(b).borderWidth=D;V(b).borderStyle="solid"}var d=S("a");d.href="http://maps.google.com/support/bin/answer.py?hl="+P(MSG_lang)+"&answer=68480";d.target="_new";R(d,W(MSG_mymaps));R(b,d);return b}function Aa(){var a=S(B);V(a).padding="5px";var b=S("h3");V(b).fontWeight="bold";R(b,W(MSG_group_standings));R(a,b);var d=S("table");V(d).border="0px";V(d).width="100%";var h=S("tbody"),g=S("tr"),i=S("td");R(i,Ua());
var l=S("td");V(l).verticalAlign="top";R(l,Va());R(g,i);R(g,l);R(h,g);R(d,h);R(a,d);var j=S("div"),m=S("a");m.href="http://www.kicker.de/em";m.target="_new";R(m,W(MSG_copyright_kicker));R(j,m);Y(j,"left");V(j).padding="3px";R(a,j);var n=Z(true);Y(n,"right");V(n).padding="3px";R(a,n);var o=S(C);V(o).clear="left";R(a,o);return a}function S(a){return document.createElement(a)}function W(a){return document.createTextNode(a)}function R(a,b){a.appendChild(b)}function V(a){return a.style}function Q(a){return a.length}
function M(a){return eval(a)}function Y(a,b){if(a.style.styleFloat===undefined)a.style.cssFloat=b;else a.style.styleFloat=b};
